version: '3.1'

services:

  adminer:
    image: adminer
    container_name: dbadmin
    restart: always
    ports:
      - 8080:8080

  db:
    image: mysql
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

